# Generated by Django 3.1.5 on 2021-01-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_products_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='products_file',
        ),
    ]
