# Generated by Django 3.1.5 on 2021-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phy_adress', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Email', 'Email'), ('Phone number', 'Phone number')], default=models.CharField(max_length=20), max_length=20)),
                ('latitude', models.IntegerField(blank=True, max_length=20, null=True)),
                ('longtitude', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
